import { redis } from './redis';

export type GuardResult = {
  allowed: boolean;
  reason?: string;
};

/**
 * Basic Token Bucket / Fixed Window rate limit implementation via Redis
 * @param identifier The unique key (e.g., IP address, user ID, HMAC'd PAN)
 * @param limit Max requests allowed
 * @param windowInSeconds Time window in seconds
 */
export async function checkRateLimit(
  identifier: string,
  limit: number,
  windowInSeconds: number
): Promise<GuardResult> {
  if (!redis) {
    // If Redis isn't configured, we fail open (or we could fail closed)
    console.warn('Redis is not configured, bypassing rate limit check');
    return { allowed: true };
  }

  try {
    const current = await redis.incr(identifier);
    if (current === 1) {
      await redis.expire(identifier, windowInSeconds);
    }
    
    if (current > limit) {
      return { allowed: false, reason: 'Rate limit exceeded' };
    }
    return { allowed: true };
  } catch (error) {
    console.error('Rate limit error:', error);
    // Fail open if Redis throws an error
    return { allowed: true };
  }
}
/**
 * Reads the current usage of a key without incrementing it.
 */
export async function getRateLimitUsage(identifier: string): Promise<number> {
  if (!redis) return 0;
  try {
    const val = await redis.get<number>(identifier);
    return val || 0;
  } catch (e) {
    console.error('getRateLimitUsage error:', e);
    return 0;
  }
}

/**
 * Explicitly increments a limit and sets expiry if it's the first hit.
 */
export async function incrementRateLimit(identifier: string, windowInSeconds: number): Promise<void> {
  if (!redis) return;
  try {
    const current = await redis.incr(identifier);
    if (current === 1) {
      await redis.expire(identifier, windowInSeconds);
    }
  } catch (e) {
    console.error('incrementRateLimit error:', e);
  }
}

/**
 * Attempts to acquire an idempotency lock for a specific request.
 * Useful to prevent double-clicks or rapid retries from triggering multiple API calls.
 * 
 * @param idempotencyKey The unique key generated by the client for this action
 * @param ttlInSeconds How long to hold the lock (e.g., 30-60 seconds for a slow API)
 * @returns true if the lock was acquired (meaning we can proceed), false if already locked
 */
export async function acquireIdempotencyLock(
  idempotencyKey: string,
  ttlInSeconds: number = 60
): Promise<boolean> {
  if (!redis || !idempotencyKey) return true; // Bypass if no Redis or no key

  try {
    // NX = Only set the key if it does not already exist
    // EX = Expire the key after ttlInSeconds
    const result = await redis.set(idempotencyKey, 'PROCESSING', {
      nx: true,
      ex: ttlInSeconds,
    });
    
    return result === 'OK';
  } catch (error) {
    console.error('Idempotency lock error:', error);
    return true; // Fail open
  }
}

/**
 * Releases the idempotency lock. 
 * Can be called when the API request finishes successfully or fails.
 */
export async function releaseIdempotencyLock(idempotencyKey: string): Promise<void> {
  if (!redis || !idempotencyKey) return;
  try {
    await redis.del(idempotencyKey);
  } catch (error) {
    console.error('Idempotency release error:', error);
  }
}
